#!/usr/bin/env node --experimental-strip-types
// Compiles YAML segment specs into a generated TS module. Workers have no
// filesystem at runtime, so curriculum content (data, not prompt text —
// build plan §5.2) gets baked into the bundle at build time, same as any
// other Workers static-data pattern.
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parse as parseYaml } from "yaml";
import { SegmentSpecSchema, type SegmentSpec } from "../src/guide-engine/segment-schema.ts";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");

function existsDir(dir: string): boolean {
  try {
    return statSync(dir).isDirectory();
  } catch {
    return false;
  }
}

function findYamlFiles(dir: string): string[] {
  if (!existsDir(dir)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...findYamlFiles(full));
    else if (entry.endsWith(".yaml") || entry.endsWith(".yml")) out.push(full);
  }
  return out;
}

// A directory is "reference" (dev/test) if it starts with an underscore
// (e.g. content/packs/_demo). Reference packs are compiled into a separate
// module so they never ship in the live curriculum bundle.
function isReferenceDir(dir: string): boolean {
  return path.basename(dir).startsWith("_");
}

function collect(files: string[]): { specs: SegmentSpec[]; errors: string[] } {
  const specs: SegmentSpec[] = [];
  const errors: string[] = [];
  for (const file of files) {
    const raw = parseYaml(readFileSync(file, "utf8"));
    const candidate = raw && typeof raw === "object" && "segment" in raw ? (raw as { segment: unknown }).segment : raw;
    const result = SegmentSpecSchema.safeParse(candidate);
    if (!result.success) {
      errors.push(`${path.relative(REPO_ROOT, file)}: ${result.error.message}`);
      continue;
    }
    specs.push(result.data);
  }
  return { specs, errors };
}

function emit(moduleName: string, sourceDir: string, outFile: string, specs: SegmentSpec[]): void {
  mkdirSync(path.dirname(outFile), { recursive: true });
  const body = `// GENERATED by scripts/compile-segment-specs.ts — do not edit by hand.
// Source: ${path.relative(REPO_ROOT, sourceDir) || "."}
import type { SegmentSpec } from "../guide-engine/segment-schema.ts";

export const ${moduleName}: SegmentSpec[] = ${JSON.stringify(specs, null, 2)};
`;
  writeFileSync(outFile, body);
  console.log(
    `Compiled ${specs.length} segment spec(s) from ${path.relative(REPO_ROOT, sourceDir) || "."} -> ${path.relative(REPO_ROOT, outFile)}`,
  );
}

function compile(sourceDir: string, outFile: string): void {
  const files = findYamlFiles(sourceDir).sort();
  const liveFiles = files.filter((f) => !isReferenceDir(path.dirname(f)));
  const refFiles = files.filter((f) => isReferenceDir(path.dirname(f)));

  const live = collect(liveFiles);
  const reference = collect(refFiles);
  const errors = [...live.errors, ...reference.errors];

  const allSpecs = [...live.specs, ...reference.specs];
  const seen = new Set<string>();
  for (const s of allSpecs) {
    if (seen.has(s.key)) errors.push(`duplicate segment key: ${s.key}`);
    seen.add(s.key);
  }

  if (errors.length > 0) {
    console.error(`Segment spec compilation FAILED — ${errors.length} error(s):`);
    for (const e of errors) console.error(`  ${e}`);
    process.exit(1);
  }

  // Live packs ship in the runtime bundle; reference packs ("./_<name>") are
  // emitted separately and never merged into SEGMENT_SPECS.
  emit("SEGMENT_SPECS", sourceDir, outFile, live.specs);
  if (reference.specs.length > 0) {
    const demoOut = path.join(path.dirname(outFile), "demo-segment-specs.ts");
    emit("DEMO_SEGMENT_SPECS", sourceDir, demoOut, reference.specs);
  }
}

const [, , sourceDirArg, outFileArg] = process.argv;
const sourceDir = sourceDirArg ? path.resolve(REPO_ROOT, sourceDirArg) : path.join(REPO_ROOT, "content", "packs");
const outFile = outFileArg
  ? path.resolve(REPO_ROOT, outFileArg)
  : path.join(REPO_ROOT, "src", "generated", "segment-specs.ts");

compile(sourceDir, outFile);
